name: flutter_firebase_recaptcha
description: reCAPTCHA widget for Firebase phone authentication
version: 1.0.1
homepage: https://github.com/psokolnikov/flutter_firebase_recaptcha

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: