name: flutter_firebase_recaptcha
description: flutter_firebase_recaptcha provides a FirebaseRecaptcha widget for creating a reCAPTCHA verifier and using that with your Firebase Phone authentication workflow.
version: 1.0.0
homepage: https://github.com/psokolnikov/flutter_firebase_recaptcha

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: